
USE [master]
GO

/****** Object:  Database [ConsultorioMedico]    Script Date: 26/10/2023 18:53:00 ******/
CREATE DATABASE [ConsultorioMedico]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ConsultorioMedico', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ConsultorioMedico.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ConsultorioMedico_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ConsultorioMedico_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

ALTER DATABASE [ConsultorioMedico] SET COMPATIBILITY_LEVEL = 160
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ConsultorioMedico].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ConsultorioMedico] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [ConsultorioMedico] SET ANSI_NULLS OFF
GO

ALTER DATABASE [ConsultorioMedico] SET ANSI_PADDING OFF
GO

ALTER DATABASE [ConsultorioMedico] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [ConsultorioMedico] SET ARITHABORT OFF
GO

ALTER DATABASE [ConsultorioMedico] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [ConsultorioMedico] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [ConsultorioMedico] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [ConsultorioMedico] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [ConsultorioMedico] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [ConsultorioMedico] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [ConsultorioMedico] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [ConsultorioMedico] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [ConsultorioMedico] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [ConsultorioMedico] SET  DISABLE_BROKER
GO

ALTER DATABASE [ConsultorioMedico] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [ConsultorioMedico] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [ConsultorioMedico] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [ConsultorioMedico] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [ConsultorioMedico] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [ConsultorioMedico] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [ConsultorioMedico] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [ConsultorioMedico] SET RECOVERY FULL
GO

ALTER DATABASE [ConsultorioMedico] SET  MULTI_USER
GO

ALTER DATABASE [ConsultorioMedico] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [ConsultorioMedico] SET DB_CHAINING OFF
GO

ALTER DATABASE [ConsultorioMedico] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [ConsultorioMedico] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [ConsultorioMedico] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [ConsultorioMedico] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

EXEC sys.sp_db_vardecimal_storage_format N'ConsultorioMedico', N'ON'
GO

ALTER DATABASE [ConsultorioMedico] SET QUERY_STORE = ON
GO

USE [ConsultorioMedico]
GO

/****** Object:  Table [Medico].[Especialidad]    Script Date: 26/10/2023 18:53:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [Medico].[Medico]    Script Date: 26/10/2023 18:53:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [Medico].[TurnoTrabajo]    Script Date: 26/10/2023 18:53:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [ConsultorioMedico] SET  READ_WRITE
GO

ALTER DATABASE [ConsultorioMedico] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)

GO

--Error de sintaxis: Sintaxis incorrecta cerca de WAIT_STATS_CAPTURE_MODE.
--ALTER DATABASE [ConsultorioMedico] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)



GO
